swagger: '2.0'
info:
  title: Koyeb Rest activity Credentials API
  description: 'The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests.

    '
  version: 1.0.0
host: app.koyeb.com
schemes:
- https
security:
- Bearer: []
tags:
- name: Credentials
paths:
  /v1/credentials:
    get:
      summary: List credentials
      operationId: ListCredentials
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/ListCredentialsReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: type
        description: (Optional) A filter for type
        in: query
        required: false
        type: string
        enum:
        - INVALID
        - USER
        - ORGANIZATION
        default: INVALID
      - name: name
        description: (Optional) A filter for name
        in: query
        required: false
        type: string
      - name: organization_id
        description: (Optional) Filter for an organization
        in: query
        required: false
        type: string
      - name: user_id
        description: (Optional) Filter for an user
        in: query
        required: false
        type: string
      - name: limit
        description: (Optional) The number of items to return
        in: query
        required: false
        type: string
      - name: offset
        description: (Optional) The offset in the list of item to return
        in: query
        required: false
        type: string
      tags:
      - Credentials
    post:
      summary: Create credential
      operationId: CreateCredential
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/CreateCredentialReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: credential
        in: body
        required: true
        schema:
          $ref: '#/definitions/CreateCredential'
      tags:
      - Credentials
  /v1/credentials/{id}:
    get:
      summary: Get credential
      operationId: GetCredential
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/GetCredentialReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: id
        in: path
        required: true
        type: string
      tags:
      - Credentials
    delete:
      summary: Delete credential
      operationId: DeleteCredential
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/DeleteCredentialReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: id
        in: path
        required: true
        type: string
      tags:
      - Credentials
    put:
      summary: Update credential
      operationId: UpdateCredential
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/UpdateCredentialReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: credential
        in: body
        required: true
        schema:
          $ref: '#/definitions/Credential'
      - name: update_mask
        in: query
        required: false
        type: string
      tags:
      - Credentials
    patch:
      summary: Update credential
      operationId: UpdateCredential2
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/UpdateCredentialReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: credential
        in: body
        required: true
        schema:
          $ref: '#/definitions/Credential'
      - name: update_mask
        in: query
        required: false
        type: string
      tags:
      - Credentials
definitions:
  GetCredentialReply:
    type: object
    properties:
      credential:
        $ref: '#/definitions/Credential'
  DeleteCredentialReply:
    type: object
  Credential.Type:
    type: string
    enum:
    - INVALID
    - USER
    - ORGANIZATION
    default: INVALID
  ListCredentialsReply:
    type: object
    properties:
      credentials:
        type: array
        items:
          $ref: '#/definitions/Credential'
      limit:
        type: integer
        format: int64
      offset:
        type: integer
        format: int64
      count:
        type: integer
        format: int64
  google.rpc.Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/google.protobuf.Any'
  ErrorWithFields:
    type: object
    properties:
      status:
        type: integer
        format: int32
      code:
        type: string
      message:
        type: string
      fields:
        type: array
        items:
          $ref: '#/definitions/ErrorField'
  UpdateCredentialReply:
    type: object
    properties:
      credential:
        $ref: '#/definitions/Credential'
  Credential:
    type: object
    properties:
      id:
        type: string
      type:
        $ref: '#/definitions/Credential.Type'
      name:
        type: string
      token:
        type: string
      description:
        type: string
      user_id:
        type: string
      organization_id:
        type: string
      updated_at:
        type: string
        format: date-time
      created_at:
        type: string
        format: date-time
      expires_at:
        type: string
        format: date-time
  google.protobuf.Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  CreateCredential:
    type: object
    properties:
      name:
        type: string
        title: Credential name
      description:
        type: string
        title: Credential description
      type:
        $ref: '#/definitions/Credential.Type'
        title: Credential type
      organization_id:
        type: string
        title: Organization id for user credential
  ErrorField:
    type: object
    properties:
      field:
        type: string
      description:
        type: string
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      code:
        type: string
      message:
        type: string
  CreateCredentialReply:
    type: object
    properties:
      credential:
        $ref: '#/definitions/Credential'
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
x-tagGroups:
- name: Introduction
  tags:
  - intro
- name: API
  tags:
  - Profile
  - Sessions
  - Users
  - organization
  - OrganizationMembers
  - OrganizationInvitations
  - OrganizationConfirmations
  - Subscriptions
  - Coupons
  - Credentials
  - Secrets
  - activity
  - Apps
  - Services
  - Deployments
  - Archives
  - RegionalDeployments
  - Instances
  - Domains
  - PersistentVolumes
  - Snapshots
  - Compose
  - Repositories
  - Logs
  - Metrics
  - Catalog
  - CatalogRegions
  - CatalogInstances
  - Usages
  - Summary
  - DockerHelper
