swagger: '2.0'
info:
  title: Koyeb Rest activity OrganizationInvitations API
  description: 'The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests.

    '
  version: 1.0.0
host: app.koyeb.com
schemes:
- https
security:
- Bearer: []
tags:
- name: OrganizationInvitations
paths:
  /v1/organization_invitations:
    get:
      summary: List Organization Invitations
      operationId: ListOrganizationInvitations
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/ListOrganizationInvitationsReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: limit
        description: (Optional) The number of items to return
        in: query
        required: false
        type: string
      - name: offset
        description: (Optional) The offset in the list of item to return
        in: query
        required: false
        type: string
      - name: statuses
        description: (Optional) Filter on organization invitation statuses
        in: query
        required: false
        type: array
        items:
          type: string
          enum:
          - INVALID
          - PENDING
          - ACCEPTED
          - REFUSED
          - EXPIRED
        collectionFormat: multi
      - name: user_id
        description: '(Optional) Filter on invitee ID. Will match both invitations sent to

          that user_id and invitations sent to the email of that user_id.

          The only valid value is the requester''s user_id'
        in: query
        required: false
        type: string
      tags:
      - OrganizationInvitations
    post:
      summary: Create Organization Invitation
      operationId: CreateOrganizationInvitation
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/CreateOrganizationInvitationReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/CreateOrganizationInvitationRequest'
      tags:
      - OrganizationInvitations
  /v1/organization_invitations/{id}:
    get:
      summary: Get Organization Invitation
      operationId: GetOrganizationInvitation
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/GetOrganizationInvitationReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: id
        description: The id of the invitation to get
        in: path
        required: true
        type: string
      tags:
      - OrganizationInvitations
    delete:
      summary: Delete Organization Invitation
      operationId: DeleteOrganizationInvitation
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/DeleteOrganizationInvitationReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: id
        description: The id of the organization invitation to delete
        in: path
        required: true
        type: string
      tags:
      - OrganizationInvitations
  /v1/organization_invitations/{id}/resend:
    post:
      summary: Resend Organization Invitation
      operationId: ResendOrganizationInvitation
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/ResendOrganizationInvitationReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: id
        description: The id of the organization invitation to resend
        in: path
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          type: object
      tags:
      - OrganizationInvitations
definitions:
  DeleteOrganizationInvitationReply:
    type: object
  CreateOrganizationInvitationReply:
    type: object
    properties:
      invitation:
        $ref: '#/definitions/OrganizationInvitation'
        title: The organization invitation sent
  google.rpc.Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/google.protobuf.Any'
  PublicUser:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
      name:
        type: string
      avatar_url:
        type: string
      github_id:
        type: string
      github_user:
        type: string
  PublicOrganization:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      plan:
        $ref: '#/definitions/Plan'
      status:
        $ref: '#/definitions/Organization.Status'
      external_id:
        type: string
  ListOrganizationInvitationsReply:
    type: object
    properties:
      invitations:
        type: array
        items:
          $ref: '#/definitions/OrganizationInvitation'
        title: The collection of organization invitations
      limit:
        type: integer
        format: int64
        title: The limit in the request
      offset:
        type: integer
        format: int64
        title: The offset in the request
      count:
        type: integer
        format: int64
        title: The total number of items
  OrganizationInvitation:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
      role:
        $ref: '#/definitions/UserRole.Role'
      status:
        $ref: '#/definitions/OrganizationInvitation.Status'
      expires_at:
        type: string
        format: date-time
      organization_id:
        type: string
      organization:
        $ref: '#/definitions/PublicOrganization'
      invitee_id:
        type: string
      invitee:
        $ref: '#/definitions/PublicUser'
      inviter_id:
        type: string
      inviter:
        $ref: '#/definitions/PublicUser'
  UserRole.Role:
    type: string
    enum:
    - INVALID
    - OWNER
    default: INVALID
  Organization.Status:
    type: string
    enum:
    - WARNING
    - LOCKED
    - ACTIVE
    - DEACTIVATING
    - DEACTIVATED
    - DELETING
    - DELETED
    default: WARNING
  ErrorWithFields:
    type: object
    properties:
      status:
        type: integer
        format: int32
      code:
        type: string
      message:
        type: string
      fields:
        type: array
        items:
          $ref: '#/definitions/ErrorField'
  Plan:
    type: string
    enum:
    - hobby
    - starter
    - startup
    - business
    - enterprise
    - internal
    - hobby23
    - no_plan
    - pro
    - scale
    - partner_csp
    - partner_csp_unit
    default: hobby
  CreateOrganizationInvitationRequest:
    type: object
    properties:
      email:
        type: string
        title: The email of the person to invite
  OrganizationInvitation.Status:
    type: string
    enum:
    - INVALID
    - PENDING
    - ACCEPTED
    - REFUSED
    - EXPIRED
    default: INVALID
  ResendOrganizationInvitationReply:
    type: object
    properties:
      invitation:
        $ref: '#/definitions/OrganizationInvitation'
        title: The organization invitation resent
  google.protobuf.Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  ErrorField:
    type: object
    properties:
      field:
        type: string
      description:
        type: string
  GetOrganizationInvitationReply:
    type: object
    properties:
      invitation:
        $ref: '#/definitions/OrganizationInvitation'
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      code:
        type: string
      message:
        type: string
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
x-tagGroups:
- name: Introduction
  tags:
  - intro
- name: API
  tags:
  - Profile
  - Sessions
  - Users
  - organization
  - OrganizationMembers
  - OrganizationInvitations
  - OrganizationConfirmations
  - Subscriptions
  - Coupons
  - Credentials
  - Secrets
  - activity
  - Apps
  - Services
  - Deployments
  - Archives
  - RegionalDeployments
  - Instances
  - Domains
  - PersistentVolumes
  - Snapshots
  - Compose
  - Repositories
  - Logs
  - Metrics
  - Catalog
  - CatalogRegions
  - CatalogInstances
  - Usages
  - Summary
  - DockerHelper
