swagger: '2.0'
info:
  title: Koyeb Rest activity Archives API
  description: 'The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests.

    '
  version: 1.0.0
host: app.koyeb.com
schemes:
- https
security:
- Bearer: []
tags:
- name: Archives
paths:
  /v1/archives:
    post:
      summary: Create Archive
      description: Create a signed URL to upload an archive.
      operationId: CreateArchive
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/CreateArchiveReply'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ErrorWithFields'
        '401':
          description: Returned when the token is not valid.
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Returned when the user does not have permission to access the resource.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Returned when the resource does not exist.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Returned in case of server error.
          schema:
            $ref: '#/definitions/Error'
        '503':
          description: Service is unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/google.rpc.Status'
      parameters:
      - name: archive
        in: body
        required: true
        schema:
          $ref: '#/definitions/CreateArchive'
      tags:
      - Archives
definitions:
  CreateArchive:
    type: object
    properties:
      size:
        type: string
        format: uint64
        description: How much space to provision for the archive, in bytes.
      project_id:
        type: string
        title: (Optional) The project ID to associate with the archive
  google.rpc.Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/google.protobuf.Any'
  ErrorWithFields:
    type: object
    properties:
      status:
        type: integer
        format: int32
      code:
        type: string
      message:
        type: string
      fields:
        type: array
        items:
          $ref: '#/definitions/ErrorField'
  google.protobuf.Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  CreateArchiveReply:
    type: object
    properties:
      archive:
        $ref: '#/definitions/Archive'
  ErrorField:
    type: object
    properties:
      field:
        type: string
      description:
        type: string
  Archive:
    type: object
    properties:
      id:
        type: string
        description: The archive id, that can be referenced when creating or updating a service.
      organization_id:
        type: string
        description: Organization owning the archive.
      upload_url:
        type: string
        description: 'The URL where to upload the archive. This URL is signed and can only be

          used to upload the archive until `valid_until`.'
      size:
        type: string
        format: uint64
        description: The provisioned space for the archive.
      created_at:
        type: string
        format: date-time
        description: Date of creation of the archive.
      deleted_at:
        type: string
        format: date-time
        description: 'This field is automatically set by Koyeb when the

          archive is garbage collected.'
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      code:
        type: string
      message:
        type: string
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
x-tagGroups:
- name: Introduction
  tags:
  - intro
- name: API
  tags:
  - Profile
  - Sessions
  - Users
  - organization
  - OrganizationMembers
  - OrganizationInvitations
  - OrganizationConfirmations
  - Subscriptions
  - Coupons
  - Credentials
  - Secrets
  - activity
  - Apps
  - Services
  - Deployments
  - Archives
  - RegionalDeployments
  - Instances
  - Domains
  - PersistentVolumes
  - Snapshots
  - Compose
  - Repositories
  - Logs
  - Metrics
  - Catalog
  - CatalogRegions
  - CatalogInstances
  - Usages
  - Summary
  - DockerHelper
